package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/iaas/terraform-provider-iaas/internal/client"
)

// Interface assertions.
var (
	_ resource.Resource                = &dbBackupPolicyResource{}
	_ resource.ResourceWithConfigure   = &dbBackupPolicyResource{}
	_ resource.ResourceWithImportState = &dbBackupPolicyResource{}
)

// NewDBBackupPolicyResource is the resource constructor registered with the
// provider.
func NewDBBackupPolicyResource() resource.Resource {
	return &dbBackupPolicyResource{}
}

// dbBackupPolicyResource manages an iaas_db_backup_policy - an off-host S3
// backup configuration for managed databases, with schedule, PITR, and
// retention settings.
//
// The attached database set is managed as an Optional SetAttribute of strings
// (managed_database UUIDs), diffed via one-at-a-time attach/detach calls on
// update, and rebuilt from the embedded "policy.managed_databases" array on
// Read. This follows the same set-diff pattern as iaas_instance_backup_policy,
// adapted for databases (managed_database_id in the request body).
//
// Route summary (verified against UserApi\DbBackupPolicyController +
// DbBackupPolicyService + DbPolicyStoreRequest/UpdateRequest/AttachRequest +
// routes/user_api.php):
//
//	INDEX   GET    /networking/db-backup-policies              (plural)
//	CREATE  POST   /networking/db-backup-policies              (plural)
//	                body {name,s3_endpoint,s3_bucket,s3_region,
//	                      s3_access_key,s3_secret_key,s3_path_prefix?,
//	                      full_backup_frequency,full_backup_time,
//	                      full_backup_day?,incremental_frequency,
//	                      pitr_enabled?,retention_full_count,
//	                      retention_incremental_days,retention_pitr_hours,
//	                      encryption_enabled?}
//	                → {success,message,policy:{id,...}}
//	SHOW    GET    /networking/db-backup-policy/{id}           (singular)
//	                → {policy:{...,managed_databases:[{id,...}]},
//	                   available_databases:[...]}
//	                NOTE: s3_access_key,s3_secret_key,encryption_key are
//	                $hidden on the model - never returned by SHOW.
//	UPDATE  PATCH  /networking/db-backup-policy/{id}          (singular)
//	                body same as CREATE (all "sometimes|required")
//	                → {success,message,policy:{...}}
//	DELETE  DELETE /networking/db-backup-policy/{id}          (singular)
//	                → {success,message}
//	ATTACH  POST   /networking/db-backup-policy/{id}/attach   body {managed_database_id}
//	DETACH  POST   /networking/db-backup-policy/{id}/detach   body {managed_database_id}
//
// KEY FINDING - WRITE-ONLY CREDENTIALS:
//   - s3_access_key, s3_secret_key are $hidden on the DbBackupPolicy model.
//     SHOW never returns them. They are sent on Create (required) and
//     optionally on Update (empty values are stripped by the service,
//     preserving the stored credentials). The provider must preserve these
//     values in state between reads (they cannot be recovered from SHOW).
//     They are marked Sensitive + the resource's Read does NOT overwrite them.
//   - encryption_key is auto-generated by the server when encryption is first
//     enabled; it is also hidden and cannot be recovered. Not exposed.
//
// All operations are SYNCHRONOUS from the API's perspective (attach dispatches
// a slave job but the HTTP response returns immediately). No billing gate.
// testConnection and reset-failures are NOT modelled (operational).
type dbBackupPolicyResource struct {
	client *client.Client
}

// dbBackupPolicyModel maps the Terraform state/plan for iaas_db_backup_policy.
type dbBackupPolicyModel struct {
	ID                       types.String `tfsdk:"id"`
	Name                     types.String `tfsdk:"name"`
	S3Endpoint               types.String `tfsdk:"s3_endpoint"`
	S3Bucket                 types.String `tfsdk:"s3_bucket"`
	S3Region                 types.String `tfsdk:"s3_region"`
	S3AccessKey              types.String `tfsdk:"s3_access_key"`
	S3SecretKey              types.String `tfsdk:"s3_secret_key"`
	S3PathPrefix             types.String `tfsdk:"s3_path_prefix"`
	FullBackupFrequency      types.String `tfsdk:"full_backup_frequency"`
	FullBackupTime           types.String `tfsdk:"full_backup_time"`
	FullBackupDay            types.Int64  `tfsdk:"full_backup_day"`
	IncrementalFrequency     types.String `tfsdk:"incremental_frequency"`
	PitrEnabled              types.Bool   `tfsdk:"pitr_enabled"`
	RetentionFullCount       types.Int64  `tfsdk:"retention_full_count"`
	RetentionIncrementalDays types.Int64  `tfsdk:"retention_incremental_days"`
	RetentionPitrHours       types.Int64  `tfsdk:"retention_pitr_hours"`
	EncryptionEnabled        types.Bool   `tfsdk:"encryption_enabled"`
	Status                   types.String `tfsdk:"status"`
	DatabaseIDs              types.Set    `tfsdk:"database_ids"`
}

// Metadata sets the resource type name → "<provider>_db_backup_policy".
func (r *dbBackupPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_db_backup_policy"
}

// Schema describes the iaas_db_backup_policy resource.
func (r *dbBackupPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a database backup policy - an off-host S3-based backup " +
			"configuration for managed databases. The policy specifies the target S3 " +
			"bucket (credentials, path prefix), the full/incremental backup schedule, " +
			"optional point-in-time recovery (PITR), and retention settings. Managed " +
			"databases are attached to the policy via the `database_ids` set attribute. " +
			"S3 credentials (`s3_access_key`, `s3_secret_key`) are write-only: the server " +
			"stores them encrypted and never returns them, so they are preserved in state " +
			"between refreshes.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "UUID of the backup policy, assigned by the API.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Display name for the backup policy. Maximum 255 characters. Updatable in place.",
			},
			"s3_endpoint": schema.StringAttribute{
				Required: true,
				Description: "Hostname (or host:port) of the S3-compatible storage endpoint. " +
					"For AWS S3 use the regional endpoint; for S3-compatible stores (RustFS, " +
					"Ceph, Wasabi) provide the custom endpoint. Updatable in place.",
			},
			"s3_bucket": schema.StringAttribute{
				Required:    true,
				Description: "Name of the S3 bucket where backups are stored. Updatable in place.",
			},
			"s3_region": schema.StringAttribute{
				Required:    true,
				Description: "AWS region (or equivalent) for the S3 bucket. Updatable in place.",
			},
			"s3_access_key": schema.StringAttribute{
				Required:  true,
				Sensitive: true,
				Description: "S3 access key ID. Stored encrypted on the server and never " +
					"returned by the API - preserved in Terraform state between refreshes. " +
					"Set to update the credentials (empty string is treated as no-change by " +
					"the server). Sensitive.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"s3_secret_key": schema.StringAttribute{
				Required:  true,
				Sensitive: true,
				Description: "S3 secret access key. Stored encrypted on the server and never " +
					"returned by the API - preserved in Terraform state between refreshes. " +
					"Set to update the credentials (empty string is treated as no-change by " +
					"the server). Sensitive.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"s3_path_prefix": schema.StringAttribute{
				Optional:    true,
				Description: "Optional path prefix inside the bucket (e.g. \"backups/prod\"). Updatable in place.",
			},
			"full_backup_frequency": schema.StringAttribute{
				Required:    true,
				Description: "How often a full backup is taken: \"daily\" or \"weekly\".",
			},
			"full_backup_time": schema.StringAttribute{
				Required:    true,
				Description: "Time of day for the full backup in HH:MM format (UTC). Updatable in place.",
			},
			"full_backup_day": schema.Int64Attribute{
				Optional: true,
				Description: "Day of the week (0=Sunday … 6=Saturday) for weekly full backups. " +
					"Required when full_backup_frequency is \"weekly\"; ignored for \"daily\".",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"incremental_frequency": schema.StringAttribute{
				Required: true,
				Description: "Frequency of incremental backups between full backups: " +
					"\"none\", \"1h\", \"2h\", \"4h\", \"6h\", or \"12h\".",
			},
			"pitr_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Description: "Whether point-in-time recovery (PITR) is enabled. When true, " +
					"WAL/binlog archives are streamed to S3. Default false.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"retention_full_count": schema.Int64Attribute{
				Required:    true,
				Description: "Number of full backups to retain (1-365).",
			},
			"retention_incremental_days": schema.Int64Attribute{
				Required:    true,
				Description: "Number of days to retain incremental backups (1-365).",
			},
			"retention_pitr_hours": schema.Int64Attribute{
				Required: true,
				Description: "Number of hours of PITR (WAL/binlog) history to retain (1-720). " +
					"Only used when pitr_enabled is true.",
			},
			"encryption_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Description: "Whether backup files are encrypted at rest using a server-generated " +
					"AES-256 key. The encryption key itself is not exposed via the API. Default false.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Description: "Current policy status: \"active\", \"error\", etc. Server-mutable; read on every refresh.",
			},
			"database_ids": schema.SetAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: "UUIDs of the managed databases attached to this backup policy, as " +
					"an order-independent set. Adding an id attaches that database to the policy " +
					"(dispatches a slave job to configure the backup agent); removing it detaches. " +
					"Each database may be attached to at most one backup policy.",
			},
		},
	}
}

// Configure pulls the shared *client.Client from the provider.
func (r *dbBackupPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Provider Data Type",
			fmt.Sprintf("Expected *client.Client, got: %T. This is a provider bug; please report it.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// Create provisions the backup policy and then attaches the configured
// database ids one by one, then reads back to get authoritative state.
func (r *dbBackupPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan dbBackupPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := dbpCreateBody(plan)

	obj, err := r.client.CreateDBBackupPolicy(ctx, body)
	if err != nil {
		resp.Diagnostics.Append(diagFromErr("Error creating database backup policy", err))
		return
	}

	id, _ := obj["id"].(string)
	if id == "" {
		resp.Diagnostics.AddError("Error creating database backup policy",
			"the create response did not contain an id")
		return
	}

	// Persist a minimal destroyable state before side-effects.
	persistMinimal := func() {
		_ = resp.State.Set(ctx, dbBackupPolicyModel{
			ID:                       types.StringValue(id),
			Name:                     plan.Name,
			S3Endpoint:               plan.S3Endpoint,
			S3Bucket:                 plan.S3Bucket,
			S3Region:                 plan.S3Region,
			S3AccessKey:              plan.S3AccessKey,
			S3SecretKey:              plan.S3SecretKey,
			S3PathPrefix:             plan.S3PathPrefix,
			FullBackupFrequency:      plan.FullBackupFrequency,
			FullBackupTime:           plan.FullBackupTime,
			FullBackupDay:            plan.FullBackupDay,
			IncrementalFrequency:     plan.IncrementalFrequency,
			PitrEnabled:              plan.PitrEnabled,
			RetentionFullCount:       plan.RetentionFullCount,
			RetentionIncrementalDays: plan.RetentionIncrementalDays,
			RetentionPitrHours:       plan.RetentionPitrHours,
			EncryptionEnabled:        plan.EncryptionEnabled,
			Status:                   types.StringValue("active"),
			DatabaseIDs:              types.SetNull(types.StringType),
		})
	}

	// Attach the configured databases one at a time.
	attachIDs, diags := stringsFromSet(ctx, plan.DatabaseIDs)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	for _, dbID := range attachIDs {
		if err := r.client.AttachDatabaseToBackupPolicy(ctx, id, dbID); err != nil {
			resp.Diagnostics.Append(diagFromErr("Error attaching database to backup policy", err))
			persistMinimal()
			return
		}
	}

	// Read back so state reflects the server-assigned values.
	state, notFound, diags := r.readState(ctx, id, plan)
	resp.Diagnostics.Append(diags...)
	if notFound {
		resp.Diagnostics.AddError("Error creating database backup policy",
			"the policy disappeared immediately after creation")
		return
	}
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Read refreshes state from the API. A 404 means the policy was deleted
// out of band - remove it from state so Terraform plans a recreate.
func (r *dbBackupPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state dbBackupPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	newState, notFound, diags := r.readState(ctx, state.ID.ValueString(), state)
	if notFound {
		resp.State.RemoveResource(ctx)
		return
	}
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, newState)...)
}

// Update applies the planned changes: patches all fields, then diffs the
// database_ids set (attach added / detach removed).
func (r *dbBackupPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state dbBackupPolicyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := state.ID.ValueString()

	// PATCH the scalar fields.
	body := dbpUpdateBody(plan, state)
	if _, err := r.client.UpdateDBBackupPolicy(ctx, id, body); err != nil {
		resp.Diagnostics.Append(diagFromErr("Error updating database backup policy", err))
		return
	}

	// Diff the database_ids set: attach added, detach removed.
	plannedIDs, diags := stringsFromSet(ctx, plan.DatabaseIDs)
	resp.Diagnostics.Append(diags...)
	stateIDs, diags := stringsFromSet(ctx, state.DatabaseIDs)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	toAttach, toDetach := ibpDiffIDs(plannedIDs, stateIDs)

	for _, dbID := range toAttach {
		if err := r.client.AttachDatabaseToBackupPolicy(ctx, id, dbID); err != nil {
			resp.Diagnostics.Append(diagFromErr("Error attaching database to backup policy", err))
			return
		}
	}
	for _, dbID := range toDetach {
		if err := r.client.DetachDatabaseFromBackupPolicy(ctx, id, dbID); err != nil {
			resp.Diagnostics.Append(diagFromErr("Error detaching database from backup policy", err))
			return
		}
	}

	// Read back so state is authoritative.
	newState, notFound, diags := r.readState(ctx, id, plan)
	resp.Diagnostics.Append(diags...)
	if notFound {
		resp.Diagnostics.AddError("Error updating database backup policy",
			"the policy disappeared during update")
		return
	}
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, newState)...)
}

// Delete removes the backup policy (the service detaches all databases first).
func (r *dbBackupPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state dbBackupPolicyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.DeleteDBBackupPolicy(ctx, state.ID.ValueString()); err != nil {
		resp.Diagnostics.Append(diagFromErr("Error deleting database backup policy", err))
		return
	}
}

// ImportState lets `terraform import iaas_db_backup_policy.x <uuid>`.
func (r *dbBackupPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// dbpCreateBody builds the body for CREATE (all required fields sent).
func dbpCreateBody(plan dbBackupPolicyModel) map[string]any {
	body := map[string]any{
		"name":                       plan.Name.ValueString(),
		"s3_endpoint":                plan.S3Endpoint.ValueString(),
		"s3_bucket":                  plan.S3Bucket.ValueString(),
		"s3_region":                  plan.S3Region.ValueString(),
		"s3_access_key":              plan.S3AccessKey.ValueString(),
		"s3_secret_key":              plan.S3SecretKey.ValueString(),
		"full_backup_frequency":      plan.FullBackupFrequency.ValueString(),
		"full_backup_time":           plan.FullBackupTime.ValueString(),
		"incremental_frequency":      plan.IncrementalFrequency.ValueString(),
		"retention_full_count":       plan.RetentionFullCount.ValueInt64(),
		"retention_incremental_days": plan.RetentionIncrementalDays.ValueInt64(),
		"retention_pitr_hours":       plan.RetentionPitrHours.ValueInt64(),
	}
	if !plan.S3PathPrefix.IsNull() && !plan.S3PathPrefix.IsUnknown() {
		body["s3_path_prefix"] = plan.S3PathPrefix.ValueString()
	}
	if !plan.FullBackupDay.IsNull() && !plan.FullBackupDay.IsUnknown() {
		body["full_backup_day"] = plan.FullBackupDay.ValueInt64()
	}
	if !plan.PitrEnabled.IsNull() && !plan.PitrEnabled.IsUnknown() {
		body["pitr_enabled"] = plan.PitrEnabled.ValueBool()
	}
	if !plan.EncryptionEnabled.IsNull() && !plan.EncryptionEnabled.IsUnknown() {
		body["encryption_enabled"] = plan.EncryptionEnabled.ValueBool()
	}
	return body
}

// dbpUpdateBody builds the body for UPDATE. Credentials are only sent when
// the plan value differs from state (prevents blanking out stored credentials
// when the user has not changed them). The server strips empty credential
// values, but we are explicit to match the service logic.
func dbpUpdateBody(plan, state dbBackupPolicyModel) map[string]any {
	body := map[string]any{
		"name":                       plan.Name.ValueString(),
		"s3_endpoint":                plan.S3Endpoint.ValueString(),
		"s3_bucket":                  plan.S3Bucket.ValueString(),
		"s3_region":                  plan.S3Region.ValueString(),
		"full_backup_frequency":      plan.FullBackupFrequency.ValueString(),
		"full_backup_time":           plan.FullBackupTime.ValueString(),
		"incremental_frequency":      plan.IncrementalFrequency.ValueString(),
		"retention_full_count":       plan.RetentionFullCount.ValueInt64(),
		"retention_incremental_days": plan.RetentionIncrementalDays.ValueInt64(),
		"retention_pitr_hours":       plan.RetentionPitrHours.ValueInt64(),
	}
	if !plan.S3PathPrefix.IsNull() && !plan.S3PathPrefix.IsUnknown() {
		body["s3_path_prefix"] = plan.S3PathPrefix.ValueString()
	}
	if !plan.FullBackupDay.IsNull() && !plan.FullBackupDay.IsUnknown() {
		body["full_backup_day"] = plan.FullBackupDay.ValueInt64()
	}
	if !plan.PitrEnabled.IsNull() && !plan.PitrEnabled.IsUnknown() {
		body["pitr_enabled"] = plan.PitrEnabled.ValueBool()
	}
	if !plan.EncryptionEnabled.IsNull() && !plan.EncryptionEnabled.IsUnknown() {
		body["encryption_enabled"] = plan.EncryptionEnabled.ValueBool()
	}
	// Only send credentials if they changed (non-empty and different from prior
	// state). This matches the service behaviour of stripping empty credential
	// fields, and avoids accidental credential blanking on unrelated updates.
	if !plan.S3AccessKey.Equal(state.S3AccessKey) && plan.S3AccessKey.ValueString() != "" {
		body["s3_access_key"] = plan.S3AccessKey.ValueString()
	}
	if !plan.S3SecretKey.Equal(state.S3SecretKey) && plan.S3SecretKey.ValueString() != "" {
		body["s3_secret_key"] = plan.S3SecretKey.ValueString()
	}
	return body
}

// readState GETs the policy and builds a full model from it. prior supplies
// fallbacks for fields the response omits (especially the write-only
// credentials that the model hides). This is the KEY preservation point:
// s3_access_key and s3_secret_key are copied from prior state because SHOW
// never returns them.
func (r *dbBackupPolicyResource) readState(ctx context.Context, id string, prior dbBackupPolicyModel) (dbBackupPolicyModel, bool, diag.Diagnostics) {
	obj, err := r.client.GetDBBackupPolicy(ctx, id)
	if err != nil {
		if client.IsNotFound(err) {
			return dbBackupPolicyModel{}, true, nil
		}
		var diags diag.Diagnostics
		diags.Append(diagFromErr("Error reading database backup policy", err))
		return dbBackupPolicyModel{}, false, diags
	}
	m, diags := dbpStateFromAPI(obj, prior)
	return m, false, diags
}

// dbpStateFromAPI builds the model from the SHOW "policy" object. Write-only
// credential fields are preserved from the prior state (not overwritten).
func dbpStateFromAPI(obj map[string]any, prior dbBackupPolicyModel) (dbBackupPolicyModel, diag.Diagnostics) {
	var diags diag.Diagnostics

	m := dbBackupPolicyModel{
		ID:                       stringFromAPI(obj, "id", prior.ID),
		Name:                     stringFromAPI(obj, "name", prior.Name),
		S3Endpoint:               stringFromAPI(obj, "s3_endpoint", prior.S3Endpoint),
		S3Bucket:                 stringFromAPI(obj, "s3_bucket", prior.S3Bucket),
		S3Region:                 stringFromAPI(obj, "s3_region", prior.S3Region),
		FullBackupFrequency:      stringFromAPI(obj, "full_backup_frequency", prior.FullBackupFrequency),
		FullBackupTime:           stringFromAPI(obj, "full_backup_time", prior.FullBackupTime),
		FullBackupDay:            optionalInt64FromAPI(obj, "full_backup_day"),
		IncrementalFrequency:     stringFromAPI(obj, "incremental_frequency", prior.IncrementalFrequency),
		RetentionFullCount:       requiredInt64FromAPI(obj, "retention_full_count", prior.RetentionFullCount),
		RetentionIncrementalDays: requiredInt64FromAPI(obj, "retention_incremental_days", prior.RetentionIncrementalDays),
		RetentionPitrHours:       requiredInt64FromAPI(obj, "retention_pitr_hours", prior.RetentionPitrHours),
		Status:                   stringFromAPI(obj, "status", prior.Status),

		// Credentials are $hidden by the model - preserve prior values so Terraform
		// does not see spurious drift and does not blank them on the next apply.
		S3AccessKey: prior.S3AccessKey,
		S3SecretKey: prior.S3SecretKey,
	}

	// Optional path prefix: map empty/absent to null so removing the prefix in
	// config clears it in state rather than perpetually falling back to prior.
	if v, ok := obj["s3_path_prefix"].(string); ok && v != "" {
		m.S3PathPrefix = types.StringValue(v)
	} else {
		m.S3PathPrefix = types.StringNull()
	}

	// Boolean fields: fall back to prior when absent.
	if v, ok := obj["pitr_enabled"].(bool); ok {
		m.PitrEnabled = types.BoolValue(v)
	} else {
		m.PitrEnabled = prior.PitrEnabled
	}
	if v, ok := obj["encryption_enabled"].(bool); ok {
		m.EncryptionEnabled = types.BoolValue(v)
	} else {
		m.EncryptionEnabled = prior.EncryptionEnabled
	}

	// Rebuild database_ids from the embedded "managed_databases" array.
	dbSet, d := dbIDSetFromAPI(obj["managed_databases"], prior.DatabaseIDs)
	diags.Append(d...)
	m.DatabaseIDs = dbSet

	return m, diags
}

// dbIDSetFromAPI converts the embedded "managed_databases" array (each element
// has an "id" field) into a types.Set of id strings. The logic mirrors
// instanceIDSetFromAPI from security_group.go.
func dbIDSetFromAPI(raw any, prior types.Set) (types.Set, diag.Diagnostics) {
	arr, _ := raw.([]any)
	if len(arr) == 0 {
		if prior.IsNull() || prior.IsUnknown() {
			return types.SetNull(types.StringType), nil
		}
		return types.SetValue(types.StringType, []attr.Value{})
	}

	elems := make([]attr.Value, 0, len(arr))
	for _, item := range arr {
		io, ok := item.(map[string]any)
		if !ok {
			continue
		}
		if idv, ok := io["id"].(string); ok && idv != "" {
			elems = append(elems, types.StringValue(idv))
		}
	}
	if len(elems) == 0 {
		if prior.IsNull() || prior.IsUnknown() {
			return types.SetNull(types.StringType), nil
		}
		return types.SetValue(types.StringType, []attr.Value{})
	}
	return types.SetValue(types.StringType, elems)
}
